Bundler/OrderedGems:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/SpaceInLambdaLiteral:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'bin/console'
    - 'tests/**'
Naming/UncommunicativeMethodParamName:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
